Adding kubeconfig
mesosphere/kubeaddons-configs pull request #223
Opened 2019-09-26 19:59 UTC by jr0d

2019-09-26 20:56 UTC, shaneutt approved these changes
One non-blocking comment (but still might be worth updating for).

Marking this as blocked on https://github.com/mesosphere/charts/pull/141 as that needs to merge before this can.

2019-09-26 20:56 UTC, shaneutt commented on templates/konvoyconfig.yaml
> +      clusterHostname: ""
:thinking: would we want to add a small comment here explaining to the reader the full context of how and why this configuration option works like this?

2019-09-27 15:51 UTC, hectorj2f commented
Yeah, let's wait until the PR is merged

2019-09-27 17:00 UTC, hectorj2f requested changes

2019-09-27 17:00 UTC, hectorj2f commented on templates/konvoyconfig.yaml
> +    version: 0.0.2
This version is 0.0.1

2019-09-27 17:22 UTC, jr0d commented
@hectorj2f fixed

2019-09-28 00:38 UTC, hectorj2f approved these changes

2019-09-28 00:39 UTC, merged