[wip] Upgrade prometheus-operator
mesosphere/kubeaddons-configs pull request #225
Opened 2019-09-28 00:11 UTC by gracedo

Upgrade to v5.19.1

2019-09-30 16:18 UTC, shaneutt commented
Looks like this is `ready`, but blocked on https://github.com/mesosphere/charts/pull/144

2019-09-30 16:19 UTC, shaneutt approved these changes

2019-09-30 16:19 UTC, shaneutt commented on templates/prometheus.yaml
> +    repo: https://gracedo.github.io/charts/staging
Let's just make sure we bump this back to mesosphere when we're unblocked before merge :+1:

2019-10-04 12:21 UTC, hectorj2f commented
@gracedo what is the state of this PR ?

2019-10-07 14:23 UTC, s12chung approved these changes

2019-10-07 14:25 UTC, s12chung requested changes
ah, keep forgetting, please update the url in line 22, the url should point to the values of the chart. the current url is a bug pointing to the wrong chart and it should be updated when the values.yaml change on the chart.

2019-10-09 15:18 UTC, shaneutt commented
@s12chung I think we're just waiting on your re-review to :heavy_check_mark: and merge this one

2019-10-09 16:37 UTC, s12chung approved these changes

2019-10-09 16:38 UTC, s12chung commented
my bad. forgot about this one. ✅

2019-10-09 17:33 UTC, merged