[WIP] Add Flagger
mesosphere/kubeaddons-configs pull request #276
Opened 2019-10-15 20:17 UTC by gpaul

Chart:
https://github.com/mesosphere/charts/pull/188

https://jira.mesosphere.com/browse/DCOS-59422

2019-11-01 13:45 UTC, shaneutt requested changes

2019-11-01 13:45 UTC, shaneutt commented on templates/flagger-loadtester.yaml
> +  annotations:
We need to add the `catalog.kubeaddons.mesosphere.io/addon-revision` annotation to both of these addons to ensure compatibility with kubeaddons-catalog. Later this should be covered by CI.

Documentation can be found at https://github.com/mesosphere/kubeaddons/tree/master/tools/catalog/README.md.

2019-11-01 13:45 UTC, shaneutt commented on templates/flagger.yaml
> +    appversion.kubeaddons.mesosphere.io/flagger: "0.19.0"
Same as above, we need the `addon-revision` annotation.

2019-11-14 10:16 UTC, gpaul commented
Closing this PR as the `/` in the branch name confuses kubeaddons. I'll open a replacement with the branch renamed to `gpaul-flagger`.

2019-11-14 10:16 UTC, closed without merging